enabled: true
auto: true
pull_requests: true
comments: true
statuses:
  skipped: true         # Green when skipped
  differences: true     # Red when style differences are found
  no_differences: true  # Green when no differences are found
request_review:
  origin: owner         # Review from the owner
  forked: none
ignore_branches:
  - "tests/*"
restylers_version: stable
